config/routes.rb
Bookmarks::Application.routes.draw do
 

  devise_for :users

  root :to => 'static_pages#home'
  get "about" => "static_pages#about"
  get "bookmarks" => "static_pages#bookmarks"
  get "bookmarks_new" => "bookmarks#new"

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  attr_accessible :name, :website
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body

  validates :username, :presence => true, :uniqueness => true, :length => { :minimum => 3, :maximum => 30 }

  # Creates User Profile
  has_one :user_profile

  has_many :bookmarks

  # after_create :create_child
  #   	UserProfile.create("user_id" => :id)

end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  	  private 
  def stored_location_for(resource_or_scope)
    nil
  end

  def after_sign_in_path_for(resource_or_scope)
    bookmarks_path
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
	def new
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def bookmarks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/my_bookmarks_helper.rb
module MyBookmarksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bookmarks/new.html.erb
<h1>Create Your New Bookmarks</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Mobile Viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Bookmarks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	        <header>
        <header class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              <%= link_to "Bookmarks", root_path, id: "logo" %>
              <nav>
                <ul class="nav pull-right">
                  <% if user_signed_in? %>
                	<li><%= link_to "My Bookmarks", bookmarks_path %></li>
                    <li><%= link_to "About", about_path %></li>
                    <li class="dropdown">
                		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
                		<ul class="dropdown-menu">
                        <li><%= link_to "My Profile", edit_user_registration_path %></li>
                  			<li><%= link_to "My Settings", edit_user_registration_path %></li>
                  			<li class="divider"></li>
                  			<li><%= link_to "Sign Out", destroy_user_session_path, :method=>'delete' %></li>
                  <% else %>
                    <li><%= link_to "About", about_path %></li>
                    <li><%= link_to "Sign In", new_user_session_path %></li>
                  <% end %>

                </ul>
              </li>
                </ul>
              </nav>
            </div>
          </div>
        </header>
        <div class="container">
            <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
            <% end %>
            <%= yield %>
        </div>
</body>
</html>

app/views/static_pages/about.html.erb
<div class="center container-narrow">
	<h1>About</h1>
	<p>This is bookmarks and this is our mission</p>
</div>

app/views/static_pages/bookmarks.html.erb
<div class="center container-narrow">
	<h1>My Bookmarks</h1>
	<p>Hello <%= current_user.username %>, this is where your bookmarks will be stored.</p>
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>Website</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= %></td>
				<td><%= %></td>
			</tr>
		</tbody>
	</table>
	<p><%= link_to "New Bookmarks", bookmarks_new_path %></p>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit jumbotron">

	<h1>Bookmarks</h1>
	
	<h2>by <a href="http://hunterbacot.com">Hunter Bacot</a></h2>
	
	<p>Store your bookmarks here, retrieve them anywhere</p>
	<br>
	<%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-large btn-primary btn-info" %>


</div>